### ISSUE TITLE
Return wrong value

### ISSUE THREAD

**Issue by LP-user1** [anburocky3/RTO-NumberPlate-Finder#1]
### Find a Bug

HI bro am **#Prasath** @LP-user1 recently i had watched your videos in you-tube, such a good youtuber you are .

- i noticed a bug in the **RTO Finder App**
- I have corrected it with below code 

` const recordFound = jsonData.find((record) => {
    return record.code === value.toUpperCase();
  });`

My app is in live - [https://lp-user1.github.io/RTO-Finder](url)

_Refer the below screenshots to notice the bug_

![Screenshot (49)](https://user-images.githubusercontent.com/97369928/214094746-87e42d93-9173-4dc6-b1d0-1dd495bf7dfa.png)

**This is my output --**

![Screenshot (50)](https://user-images.githubusercontent.com/97369928/214094633-7652712a-a3bf-4b20-be01-618da3fa2b38.png)

**Comment by anburocky3** [comment]
@LP-user1 Thank you, the code can be improved even more. Using Arrow Function.

```js
const recordFound = jsonData.find((record) =>  record.code === value.toUpperCase());
```

**Comment by LP-user1** [comment]
@anburocky3  Thank you bro 👍
